[tool.poetry]
name = "linguisage-authentification"
version = "0.1.0"
description = ""
authors = ["iRespectOnlyYen <MyNameIIIypuk@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.12.1"
fastapi = {extras = ["all"], version = "^0.104.1"}
asyncpg = "^0.29.0"
black = "^23.10.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.23"}
sqlalchemy-utils = "^0.41.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
